version: '3.8'

services:
  # Main application
  voice-assistant-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_here}
      - DATABASE_URL=postgresql://voice_user:voice_pass@postgres:5432/voice_assistant
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - voice-assistant-network

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=voice_assistant
      - POSTGRES_USER=voice_user
      - POSTGRES_PASSWORD=voice_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voice-assistant-network

  # Redis for session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - voice-assistant-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@voiceassistant.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - voice-assistant-network

volumes:
  postgres_data:
  redis_data:

networks:
  voice-assistant-network:
    driver: bridge 